# Data Science- K-Nearest Neighbors

### In this advanced data science topic, we will be exploring how the K-Nearest Neighbors (KNN) algorithm works. It will utilize concepts taught in module 3 such as pandas and dataframes. For this project we will be using a dataset from https://catalog.data.gov/dataset/covid-19-vaccinations-by-zip-code

## Import Stuff

In [ ]:
# Install and import all the neccessary stuff

%pip install scikit-learn
%pip install pandas

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

## Load data

### First thing we will do is load the data into pandas and look at its structure. Let's take a look at the first few rows using ```df.head()``` to get a look at what we have.

### We also want to run ```df.info``` to get some metadata to save us some time from counting rows and columns by hand.

In [24]:

# Import the dataset
df = pd.read_csv('COVID-19_Vaccinations_by_ZIP_Code.csv', dtype={"Zip Code": "string", "Date": "string", "ZIP Code Location": "string", "Row_ID": "string"})

# Display the first few rows of the dataset
df.head()

,Zip Code,Date,Total Doses - Daily,Total Doses - Cumulative,1st Dose - Daily,1st Dose - Cumulative,1st Dose - Percent Population,Vaccine Series Completed - Daily,Vaccine Series Completed - Cumulative,Vaccine Series Completed - Percent Population,...,Vaccine Series Completed - Daily - Age 12+,Vaccine Series Completed - Daily - Age 18+,Vaccine Series Completed - Daily - Age 65+,Bivalent - Daily - Age 0-17,Bivalent - Daily - Age 18-64,Bivalent - Daily - Age 18+,Bivalent - Daily - Age 65+,Population,ZIP Code Location,Row_ID
0,60601,01/25/2021,55,1544,38,1084,0.072,17,459,0.030,...,17.0,17,2,0,0,0,0,15083.0,POINT (-87.622844 41.886262),60601-20210125
1,60601,01/26/2021,65,1609,41,1125,0.075,24,483,0.032,...,24.0,24,1,0,0,0,0,15083.0,POINT (-87.622844 41.886262),60601-20210126
2,60601,01/27/2021,73,1682,56,1181,0.078,17,500,0.033,...,17.0,17,2,0,0,0,0,15083.0,POINT (-87.622844 41.886262),60601-20210127
3,60601,02/07/2021,23,2412,17,1745,0.116,6,667,0.044,...,6.0,6,2,0,0,0,0,15083.0,POINT (-87.622844 41.886262),60601-20210207
4,60601,02/08/2021,56,2468,38,1783,0.118,18,685,0.045,...,18.0,18,5,0,0,0,0,15083.0,POINT (-87.622844 41.886262),60601-20210208

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58020 entries, 0 to 58019
Data columns (total 36 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Zip Code                                        58020 non-null  string
 1   Date                                            58020 non-null  string
 2   Total Doses - Daily                             58020 non-null  int64
 3   Total Doses - Cumulative                        58020 non-null  int64
 4   1st Dose - Daily                                58020 non-null  int64
 5   1st Dose - Cumulative                           58020 non-null  int64
 6   1st Dose - Percent Population                   56086 non-null  float64
 7   Vaccine Series Completed - Daily                58020 non-null  int64
 8   Vaccine Series Completed - Cumulative           58020 non-null  int64
 9   Vaccine Series Completed  - Percent Population  56086 non-null  float64
 10  Bivalent - Daily                                58020 non-null  int64
 11  Bivalent - Cumulative                           58020 non-null  int64
 12  Bivalent - Percent Population                   57336 non-null  float64
 13  Total Doses - Daily - Age 5+                    49260 non-null  float64
 14  Total Doses - Daily - Age 12+                   49260 non-null  float64
 15  Total Doses - Daily - Age 18+                   49260 non-null  float64
 16  Total Doses - Daily - Age 65+                   49260 non-null  float64
 17  1st Dose - Daily - Age 0-17                     58020 non-null  int64
 18  1st Dose - Daily - Age 18-64                    58020 non-null  int64
 19  1st Dose - Daily - Age 5+                       49260 non-null  float64
 20  1st Dose - Daily - Age 12+                      49260 non-null  float64
 21  1st Dose - Daily - Age 18+                      58020 non-null  int64
 22  1st Dose - Daily - Age 65+                      58020 non-null  int64
 23  Vaccine Series Completed - Daily - Age 0-17     58020 non-null  int64
 24  Vaccine Series Completed - Daily - Age 18-64    58020 non-null  int64
 25  Vaccine Series Completed - Daily - Age 5+       49260 non-null  float64
 26  Vaccine Series Completed - Daily - Age 12+      49260 non-null  float64
 27  Vaccine Series Completed - Daily - Age 18+      58020 non-null  int64
 28  Vaccine Series Completed - Daily - Age 65+      58020 non-null  int64
 29  Bivalent - Daily - Age 0-17                     58020 non-null  int64
 30  Bivalent - Daily - Age 18-64                    58020 non-null  int64
 31  Bivalent - Daily - Age 18+                      58020 non-null  int64
 32  Bivalent - Daily - Age 65+                      58020 non-null  int64
 33  Population                                      56086 non-null  float64
 34  ZIP Code Location                               57053 non-null  string
 35  Row_ID                                          58020 non-null  string
dtypes: float64(12), int64(20), string(4)
memory usage: 15.9 MB